<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_radius" value="0.05" />
    <xacro:property name="lidar_length" value="0.15" />

    <link name="lidar_link">
      <visual>
        <geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_length}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <material name="grey" />
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_length}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <xacro:cylinder_inertia m="0.3" r="${lidar_radius}" l="${lidar_length}"
                              o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <joint name="mobile_base_lidar_joint" type="fixed">
      <parent link="base_link" />
      <child link="lidar_link" />
      <origin xyz="${base_length/2.5} 0 ${base_height}" rpy="0 0 0"/>
    </joint>

   <gazebo reference="lidar_link">
        <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
          <render_engine>ogre2</render_engine>
        </plugin>
        <sensor name="gpu_lidar" type="gpu_lidar">
          <pose relative_to="lidar_link">0 0 0 0 0 0</pose>
          <topic>lidar</topic>
          <update_rate>30</update_rate>
          <ray>
              <scan>
                  <horizontal>
                      <samples>720</samples>
                      <resolution>1</resolution>
                      <min_angle>-1.396263</min_angle>
                      <max_angle>1.396263</max_angle>
                  </horizontal>
                  <vertical>
                      <samples>1</samples>
                      <resolution>0.01</resolution>
                      <min_angle>0</min_angle>
                      <max_angle>0</max_angle>
                  </vertical>
              </scan>
              <range>
                  <min>0.08</min>
                  <max>10.0</max>
                  <resolution>0.01</resolution>
              </range>
          </ray>
          <frame_id>lidar_link</frame_id>
          <always_on>1</always_on>
          <visualize>true</visualize>
        </sensor>
    </gazebo>

</robot>