<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="box_length" value="0.1" />
    <xacro:property name="box_width" value="0.1" />
    <xacro:property name="box_height" value="0.02" />
    <xacro:property name="arm_radius" value="0.02" />
    <xacro:property name="arm_length" value="0.3" />

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" x="${box_length}" y="${box_width}" z="${box_height}"
                           o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <link name="arm_link">
         <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}" />
            </geometry>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}" />
            </geometry>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0" />             
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${arm_radius}" l="${arm_length}"
                                    o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <link name="hand_link">
         <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}" />
            </geometry>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}" />
            </geometry>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0" />             
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${arm_radius}" l="${arm_length}"
                                    o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>


    <joint name="base_forearm_joint" type="revolute">
        <parent link="arm_base_link"/>
        <child link="arm_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="1.5708" effort="100" velocity="100"/>
        <dynamics damping="0.3" friction="0.3"/>

    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <parent link="arm_link"/>
        <child link="hand_link"/>
        <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="1.5708" effort="100" velocity="100"/>
        <dynamics damping="0.3" friction="0.3"/>

    </joint> 
</robot>